CREATE TABLE relatorios_cadpo(
    Registro_ANS VARCHAR(255),
    CNPJ VARCHAR(20),
    Razao_Social VARCHAR(55),
    Nome_Fantasia VARCHAR(55),
    Modalidade VARCHAR(55),
    Logradouro VARCHAR(255),
    Numero INT,
    Complemento VARCHAR(185),
    Bairro VARCHAR(255),
    Cidade VARCHAR(25),
    UF VARCHAR(5),
    CEP VARCHAR(9),
    DDD INT,
    Telefone INT,
    Fax VARCHAR(255),
    Endereco_eletronico VARCHAR(255),
    Representante VARCHAR(55),
    Cargo_Representante VARCHAR(55),
    Regiao_de_Comercializacao VARCHAR(255),
    Data_Registro_ANS VARCHAR(255)
);

CREATE TABLE T1_2023(
    DATA DATE,
    REG_ANS VARCHAR(10),
    CD_CONTA_CONTABIL VARCHAR(55),
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL DECIMAL,
    VL_SALDO_FINAL DECIMAL
);

CREATE TABLE T2_2023(
    DATA DATE,
    REG_ANS VARCHAR(10),
    CD_CONTA_CONTABIL VARCHAR(55),
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL DECIMAL,
    VL_SALDO_FINAL DECIMAL
);

CREATE TABLE T3_2023(
    DATA DATE,
    REG_ANS VARCHAR(10),
    CD_CONTA_CONTABIL VARCHAR(55),
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL DECIMAL,
    VL_SALDO_FINAL DECIMAL
);

CREATE TABLE T4_2023(
    DATA VARCHAR(10),
    REG_ANS VARCHAR(10),
    CD_CONTA_CONTABIL VARCHAR(55),
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL DECIMAL,
    VL_SALDO_FINAL DECIMAL
);

LOAD DATA LOCAL INFILE '/home/gabriel/Projects/testes/teste3_databases/files/Relatorio_cadop.csv'
INTO TABLE relatorios_cadpo
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/gabriel/Projects/testes/teste3_databases/files/1T2023.csv'
INTO TABLE T1_2023
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/gabriel/Projects/testes/teste3_databases/files/2T2023.csv'
INTO TABLE T2_2023
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/gabriel/Projects/testes/teste3_databases/files/3T2023.csv'
INTO TABLE T3_2023
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/gabriel/Projects/testes/teste3_databases/files/4T2023.csv'
INTO TABLE T4_2023
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT r.Razao_Social, SUM(t.VL_SALDO_FINAL) AS Total_Despesas
FROM T4_2023 t
JOIN relatorios_cadpo r ON t.REG_ANS = r.Registro_ANS
WHERE t.DESCRICAO LIKE '%SINISTROS CONHECIDOS OU AVISADOS DE ASSISTÊNCIA A SAÚDE%'
GROUP BY r.Razao_Social
ORDER BY Total_Despesas DESC
LIMIT 10

SELECT r.Razao_Social, SUM(t.VL_SALDO_FINAL) AS Total_Despesas
FROM (
    SELECT REG_ANS, VL_SALDO_FINAL FROM T1_2023 WHERE DESCRICAO LIKE '%SINISTROS CONHECIDOS OU AVISADOS DE ASSISTÊNCIA A SAÚDE%'
    UNION ALL
    SELECT REG_ANS, VL_SALDO_FINAL FROM T2_2023 WHERE DESCRICAO LIKE '%SINISTROS CONHECIDOS OU AVISADOS DE ASSISTÊNCIA A SAÚDE%'
    UNION ALL
    SELECT REG_ANS, VL_SALDO_FINAL FROM T3_2023 WHERE DESCRICAO LIKE '%SINISTROS CONHECIDOS OU AVISADOS DE ASSISTÊNCIA A SAÚDE%'
    UNION ALL
    SELECT REG_ANS, VL_SALDO_FINAL FROM T4_2023 WHERE DESCRICAO LIKE '%SINISTROS CONHECIDOS OU AVISADOS DE ASSISTÊNCIA A SAÚDE%'
) t
JOIN relatorios_cadpo r ON t.REG_ANS = r.Registro_ANS
GROUP BY r.Razao_Social
ORDER BY Total_Despesas DESC
LIMIT 10;